baseURL: https://willemmirkovich.github.io
languageCode: en-us
title: Willem Mirkovich Blog
theme: "PaperMod"

menu:
  main:
    - identifier: Resume
      name: Resume 
      url: /pdf/Resume.pdf 
      weight: 20
    - identifier: Archives
      name: Archives
      url: /archives/ 
      weight: 20
    - identifier: Tags
      name: Tags
      url: /tags/ 
      weight: 20
    - identifier: Search
      name: Search
      url: /search/ 
      weight: 20

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary

params:

    homeInfoParams:
        Title: Welcome! 
        Content: My name is Willem Mirkovich, and I am a Software Engineer. 
          This is my personal site/blog, feel free to peruse and see what I 
          am up to.

    socialIcons:
        - name: github
          url: "https://github.com/willemmirkovich"
        - name: linkedin
          url: "https://www.linkedin.com/in/willem-mirkovich-48a417153/"

publishDir: docs # location of output site